# -*- coding: utf-8 -*-
"""SHIPS_reader_V2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KKz9FB0cmP1T-u0Ktbwv8U_07QinBdA0
"""

import numpy as np
import xarray as xr
import pandas as pd
# from google.colab import drive
import datetime
# drive.mount('/content/drive')

fname = 'lsdiaga_1982_2019_sat_ts.dat'
BASIN_name = 'ATLANTIC'
fname_save = 'SHIPS_predictors_full_{basin}.csv'.format(basin=BASIN_name)

"""Load file

If line is HEAD, set NAME to HEAD[0]; set DATE to HEAD[1], set CASE_TIME to HEAD[2]

Combine DATE and CASE_TIME

If line is LAST, increase case_count by 1

Else, other stuff
"""

SHIPS_all = pd.DataFrame()
chunk_count = 0
case_count = 0
with open(fname) as infile:
  for line in infile:
    line_s = line.split()
    # If HEAD, keep the storm NAME and DATE/TIME
    if line_s[-1] == 'HEAD':
      NAME = line_s[0]
      DATE = line_s[1]
      CASE_TIME = line_s[2]
      DATE_fm = datetime.datetime.strptime(DATE,'%y%m%d')
      DATE_full = DATE_fm + pd.DateOffset(hours=int(CASE_TIME))
      df_new = pd.DataFrame(columns={'CASE','NAME','DATE_full'})
    #
    elif (line_s[-1] == 'LAST'):
      df_new['NAME'] = NAME
      df_new['DATE_full'] = DATE_full
      if case_count == 0:
        df_new['CASE'] = 0
      else:
        df_new['CASE'] = case_count
      SHIPS_all = SHIPS_all.append(df_new)
      case_count = case_count + 1
      if np.mod(case_count,200) == 0:
        SHIPS_all.to_csv(fname_save)
        print('saved at case ',case_count)
      del df_new
      print('on to case ',case_count)
    #
    elif (line_s[-1] != 'HEAD') | (line_s[-1] != 'LAST'):
      line_len = len(line_s)
      # Predictors that start at time = -12 h
      if (line_len == 24):
        #
        df_new[line_s[-1]] = line_s[0:-1]
      # For predictors with a number to the right of them (RSST, etc), add a variable that is RSST age (or whatever)
      elif line_len == 25:
        df_new[line_s[-2]] = line_s[0:-2]
        df_new[[line_s[-2]+'_AGE']] = line_s[-1]
      # Predictors that start at time = 0 h (need to pad first two rows)
      elif line_len == 22:
        new_col = pd.Series(line_s[0:-1],name=line_s[-1])
        new_col.loc[-1] = ""
        new_col.loc[-2] = ""
        new_col = new_col.sort_index().reset_index().drop(columns='index')
        df_new[line_s[-1]] = new_col
      # Predictors that start at time = 0 h but also have a number to the right (age term)
      elif line_len == 23:
      # For last, append everything to big file and move on
        new_col = pd.Series(line_s[0:-2],name=line_s[-2])
        new_col.loc[-1] = ""
        new_col.loc[-2] = ""
        new_col = new_col.sort_index().reset_index().drop(columns='index')
        df_new[line_s[-2]] = new_col
        df_new[[line_s[-2]+'_AGE']] = line_s[-1]

